# Homework 2: NumPy Array Creation and Manipulation

**Objective:** Familiarize with basic NumPy array creation, attributes, and manipulation techniques.

**Instructions:** Complete the following code cells in this Jupyter Notebook. Provide explanations in the markdown cells and comments for your code as necessary.



### Task 1: Array Creation

1.1. In the code cell below, using NumPy to create a one-dimensional array of numbers from 0 to 9. Name the array `arr1d` and print its contents.


In [5]:
import numpy as np

arr1d = np.array([0,1,2,3,4,5,6,7,8,9])
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1.2. In the code cell below, create a two-dimensional 3x3 array filled with zeros. Name this array `arr2d_zeros`. Print its contents.

In [13]:
arr2d_zeros = np.array([np.zeros(3), np.zeros(3), np.zeros(3)])

arr2d_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

1.3. Read the documentation for [numpy.full()](https://numpy.org/doc/stable/reference/generated/numpy.full.html). Use the full() method to create an array of 10 elements, each element being 5. Name this array `arr_constant` and print its contents.

In [23]:
arr_constant = np.full((1, 10), 5)

print(arr_constant)

[[5 5 5 5 5 5 5 5 5 5]]


### Task 2: Array Attributes
2.1. In the code cell below, Print the shape, size, and data type of the array created in Task 1.1.

In [31]:
print(arr1d.shape)
print(arr1d.size)
print(arr1d.dtype)

(10,)
10
int32


2.2. In the code cell below, reshape the array from Task 1.1 into a 2x5 matrix named `arr1d_reshaped`. Print the reshaped array.

In [35]:
arr1d_reshaped = arr1d.reshape(2,5)

print(arr1d_reshaped)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Task 3: Array Operations
3.1. Read the documentation on[numpy.random.randint()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)  
In the code cell below, use numpy.random.randint() to create an array named `arr_random` that contains 10 random integers between 1 and 100.
Print the contents of `arr_random`

In [42]:
arr_random = np.random.randint(100, size = 10)

print(arr_random)

[95 88 80 44 61 37 84 17 35 60]


3.2. Create a mask named `bool_filter` which will filter out the elements greater than 50 in the array created in Task 3.1.
Print the contents of `bool_filter` and the contents of the array in 3.1 with the filter mask applied.

In [48]:
bool_filter = arr_random > 50

print(bool_filter)

arr_filtered = arr_random[bool_filter]

print(arr_filtered)


[ True  True  True False  True False  True False False  True]
[95 88 80 61 84 60]


3.3. Given the two arrays in the code cell below, perform element-wise addition, subtraction, multiplication, and division on two arrays. Print the results of each operation.

In [49]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
#Put your code below

arrAdd = arr1 + arr2
arrSub = arr1 - arr2
arrMult = arr1 * arr2
arrDiv = arr1 / arr2

print(arrAdd)
print(arrSub)
print(arrMult)
print(arrDiv)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]


3.4. Given the matrix below, complete the line of code needed to Transpose the matrix.

In [50]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The matrix is:")
print(matrix)
transposed_matrix = matrix.transpose()  #complete this line
print("and the transposed matrix is:")
print(transposed_matrix)

The matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
and the transposed matrix is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
